GET http://localhost:3000/api/hello

###
POST http://localhost:3000/api/chats
Content-Type: application/json

{
  "message": "hello world"
}
###
GET http://localhost:3000/api/chats
Content-Type: application/json


###
@chatId = 714d1e51-c6ad-4de1-bc36-cdf86aab75a4

GET http://localhost:3000/api/chats/{{chatId}}/messages

###
POST  http://localhost:3000/api/chats/{{chatId}}/messages
Content-Type: application/json

{
  "message": "Eu estou testando a API"
}

###
@messageId = b4339188-bd34-433a-bc3d-9e149fdb8ebd

GET http://localhost:3000/api/messages/{{messageId}}/events